spring:
  application:
    name: dropbox
  datasource:
    url: jdbc:mysql://localhost:3306/dropbox
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# src/main/resources/application.yml
file:
  upload-dir: /Users/pawandeep.singh/Desktop/personal_projects/dropbox/dropbox-backend/uploaded_files
  allowed-extensions:
    - txt
    - jpg
    - png
    - json


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] - %msg%n"



